linters-settings:
  depguard:
    list-type: blacklist
    packages:
    # logging is allowed only by logutils.Log, logrus
    # is allowed to use only in logutils package
    #      - github.com/sirupsen/logrus
    packages-with-error-message:
  #      - github.com/sirupsen/logrus: "logging is allowed only by logutils.Log"
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  exhaustive:
    # check switch statements in generated files also
    check-generated: false
    # indicates that switch statements are to be considered exhaustive if a
    # 'default' case is present, even if all enum members aren't listed in the
    # switch
    default-signifies-exhaustive: true
  gci:
    local-prefixes: github.com/golangci/golangci-lint
  goconst:
    min-len: 2
    min-occurrences: 2
  #  gocritic:
  ##    enabled-tags:
  ##      - diagnostic
  ##      - experimental
  ##      - opinionated
  ##      - performance
  ##      - style
  #    disabled-checks:
  #      - dupImport # https://github.com/go-critic/go-critic/issues/845
  #      - ifElseChain
  #      - octalLiteral
  #      - whyNoLint
  #      - wrapperFunc
  #      - hugeParam
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  revive:
    # see https://github.com/mgechev/revive#available-rules for details.
    ignore-generated-header: true
    severity: warning
    confidence: 0.8
    error-code: 2
    warning-code: 1
    rules:
      - name: indent-error-flow
      #      - name: add-constant
      #        arguments: [{maxLitCount = "3",allowStrs ="\"\"",allowInts="64",allowInts="0",allowInts="18",allowFloats="0.0"}]
      - name: atomic
      - name: bare-return
      - name: blank-imports
      - name: call-to-gc
      - name: cognitive-complexity
        arguments: [ 10 ]
      - name: confusing-naming
      - name: constant-logical-expr
      - name: context-as-argument
      - name: context-keys-type
      - name: cyclomatic
        arguments: [ 10 ]
      - name: deep-exit
      - name: defer
        arguments: [ [ "call-chain","loop","recover","return","method-call" ] ]
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: function-result-limit
        arguments: [ 4 ]
      - name: function-length
        arguments: [ 50,90 ]

  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks:
          - argument
          - case
          - condition
          - return
        ignored-numbers:
          - "0"
          - "10"
          - "64"
          - "100"
          - "1e6"
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    # - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

    # don't enable:
    # - asciicheck
    # - scopelint
    # - gochecknoglobals
    # - gocognit
    # - godot
    # - godox
    # - goerr113
    # - interfacer
    # - maligned
    # - nestif
    # - prealloc
    # - testpackage
    # - revive
    - wsl

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test.go
      linters:
        - gomnd

    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"

run:
  skip-dirs:
    - test/testdata_etc
    - internal/cache
    - internal/renameio
    - internal/robustio
  skip-files:
    - 无用.go
    - 'pay/tiger/form_mapping.go' # 从gin导入
    - '(.+)_test\.go'
    - '(.+)_import\.go' # 导入的文件